/*console.log("Supermercado Cumelen");
console.log("gaseosa coca cola por 2.25 lts", "50 unidades");
console.log("fideos soperos lucchetti ", "35 unidades");
console.log("pure de tomate arcor", "40 unidades");
console.log("arroz primavera arcor", "20 unidades");
console.log("caldo para sopa por 12 cubos", "25 unidades");
console.log("fideos soperos mattarazzo", "30 unidades");
console.log("atun por 250 gr al natural", "30 unidades");
console.log("papel higienico scott por 4 rollos", "30 unidades");
console.log("detergente por 500 cm3 ala", "25 unidades");
console.log("aceite natura por 900 cm3", "50 unidades");
*/

let nombreDeSuper: string = "Cumelen";
let producto1: string = "coca cola";
let stock1: number = 45;
let precio1: number = 190;
let producto2: string = "mermelada";
let stock2: number = 35;
let precio2: number = 150;
let producto3: string = "galletitas";
let stock3: number = 50;
let precio3: number = 120;
let producto4: string = "pate";
let stock4: number = 25;
let precio4: number = 60;
let producto5: string = "mayonesa";
let stock5: number = 30;
let precio5: number = 180;
let producto6: string = "aceite";
let stock6: number = 40;
let precio6: number = 250;
let producto7: string = "fideos";
let stock7: number = 55;
let precio7: number = 120;
let producto8: string = "azucar";
let stock8: number = 100;
let precio8: number = 110;
let producto9: string = "yerba";
let stock9: number = 50;
let precio9: number = 350;
let producto10: string = "pan rallado";
let stock10: number = 30;
let precio10: number = 170;
console.log("el nombre del super es:" + nombreDeSuper);
console.log ("se compraron" stock9 - 48, producto9, "por $" precio9*2, "queda en stock" stock9-2);
